name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/colashn65/0612-actions:1.0 .
      - run: docker push ghcr.io/colashn65/0612-actions:1.0
      - run: ssh -o "StrictHostKeyChecking no" 'colashn65-0612-k3uooqgp9g1#Jk4V97dfV9qpPtOO1v9piJcWKp9sMtlt@colashn65-0612-k3uooqgp9g1.ssh.ws-eu106.gitpod.io' "cd /workspace/06.12 && docker compose pull && docker compose up -d";
